inspect:
  dataset_name: testing_inspect_maskgen
  port: 5050
  only_include_tags:
    - missing_white


refine:
  only_include_tags:
    - missing_white
  
  filter_db_by_final_voxel_tags: # filters the voxel database by specific final voxel tags 
    - good

  # Morphological operations and HSV color ranges for mask generation.
  missing_red:
    exr_thresh: 60
    saturation_thresh: 20
    opening_kernel_size: 0
    closing_kernel_size: 0
    erosion_kernel_size: 0

  missing_white: # focus of v value
    luminance_thresh: 200
    opening_kernel_size: 0
    closing_kernel_size: 0
    erosion_kernel_size: 0

  present_mat: #gray or black pixels
    hsv_lower: [15, 54, 46]
    hsv_upper: [21, 94, 150]
    opening_kernel_size: 3
    closing_kernel_size: 4
    erosion_kernel_size: 2


canonical_tag_mapping: # ensures user defined tags are mapped to canonical tags (canonical: user defined)
  missing_red: red
  missing_white: white
  present_mat: mat
  bad: bad
  other: other
  ignore: ignore
  good: good

relabel:
  annot_session_key: cvat_mask_refine_run_001
  task_name: test mask_gen relabeling
  label_field: refined_mask # either initial_mask or refined_mask
  only_tags:
    - missing_white

export_cvat:
  task_ids: 
    - 288  # CVAT task ID for exporting annotations
