inspect:
  dataset_name: testing_inspect_maskgen
  port: 5050


refine:
  # Morphological operations and HSV color ranges for mask generation.
  missing_red:
    hsv_lower: [0, 100, 100]
    hsv_upper: [179, 255, 255]
    opening_kernel_size: 3
    closing_kernel_size: 4
    erosion_kernel_size: 3

  missing_white:
    hsv_lower: [0, 0, 150]
    hsv_upper: [180, 255, 255]
    # lower: [0, 0, 200]
    # upper: [180, 30, 255]
    opening_kernel_size: 3
    closing_kernel_size: 0
    erosion_kernel_size: 3

  present_mat: #gray or black pixels
    hsv_lower: [15, 54, 46]
    hsv_upper: [21, 94, 150]
    opening_kernel_size: 3
    closing_kernel_size: 4
    erosion_kernel_size: 2
