# Hydra defaults and settings. 
mode: ??? # Options: test, run_pipeline

defaults:
  - paths: default
  - mask_refine: default
  - inspect: default
  - _self_

hydra:
  run:
    dir: ${paths.logdir}/${job.job_now}
   
project:
  name: first_test_001

pipeline:
  # - detect_weeds
  # - unet_segment_weeds
  - mask_inspect
  # - mask_refine

test:
  enabled: true

mask_inspect:
  save2lts: false

general:
  task: # Leave empty as placeholder

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${paths.datadir}/${job.job_now}
