name: field_train
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - opencv
  - numpy
  - pandas
  - matplotlib
  - pillow
  - tqdm
  - pyyaml
  - scikit-image
  - hydra-core
  - wandb
  - omegaconf
  - fiftyone
  - pip
  - pip:
      # Segmentation & Metrics
      - torch
      - torchvision
      - pytorch-lightning
      - segmentation-models-pytorch
      - torchmetrics
      # GPU utility
      - gputil
      # Optional / Future use
      - ultralytics  # only needed if you explicitly use YOLO-based models
