species_images:
  ragweed parthenium: 5
  palmer amaranth: 5

seed: 42

# species in the agir_field_db:
# ragweed parthenium
# palmer amaranth
# smooth pigweed
# goosegrass
# prickly sida
# large crabgrass
# jimson weed
# horseweed
# johnsongrass
# common waterhemp
# hophornbeam copperleaf
# broadleaf signalgrass
# spiny amaranth
# yellow nutsedge
# common cocklebur
# giant ragweed
# giant foxtail
# yellow foxtail
# velvetleaf
# fall panicum
# common ragweed
# sicklepod
# barnyardgrass
# ryegrass
# silverleaf nightshade
# field bindweed
# common sunflower
# waterhemp
# jungle rice
# kochia
# texas millet
# common lambsquarters
# crabgrass (large or other spp.)
# canada thistle
# redroot pigweed
# devil’s claw
# junglerice
# ladysthumb