# Top‐level Hydra configuration. Lists each config group in the "defaults:" section.
# Order matters: later entries can override earlier keys.
# Hydra defaults and settings. 
defaults:
  - paths: default             # all filesystem paths (data_dir, model_save_dir, etc.)
  - model: unet                # architecture group: unet (can switch to deeplabv3plus, etc.)
  - train: default             # training hyperparameters + Lightning Trainer settings
  - augment: default           # data augmentation transforms
  - preprocess: default        # resizing / normalization / cropping
  - maskgen: default           # mask generation/refinement settings
  - inference: default         # inference & evaluation settings
  - evaluation: default         # evaluation metrics and settings
  - mask_gen: default
  - override hydra/job_logging: custom # a custom logging config (Hydra job logger override)
  - _self_                     # Ensures overriding behavior

# Any keys you want to sit “outside” those groups:
project:
  # Note: project_name typically duplicated from projects.field.project_name, but putting here
  name: test # or field


mode: preprocess                  # one of: mask_gen / preprocess / train / inference

tasks: # TODO: make the other tasks bool key/values
  preprocess:
    pad_gridcrop_resize: false
    train_val_test_split: false
    compute_data_stats:   true
  maskgen:
    sync: false # skip for now; copies the most up-to-date version of the files needed to run the mask_gen mode from LTS to here
    detect_weeds: true
    unet_segment_weeds: true
    mask_inspect: true
    mask_refine: true
  train:
    - train
  inference:
    - inference

# You can add any global flags here if desired, e.g. debug: false, seed: 42, etc.
hydra:
  run:
    # base of all outputs for train mode
    dir: ${paths.project_train_dir}/version_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ${paths.project_train_dir}/multirun

test:
  enabled: true

mask_inspect: # TODO: what is this for?
  save2lts: false

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${paths.data_dir}/${job.job_now}
