# Hydra defaults and settings
defaults:
  - paths: default # or your_paths_template
  - unet_conf: default
  - _self_

hydra:
  run:
    dir: ${paths.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
  # - crop_and_resize
  # - unet_segmentation
  - inference
  
project_name: FIELD
task: # Leave empty as placeholder

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${data.datadir}/${job.job_now}