# Hydra defaults and settings
defaults:
  - paths: default # or your_paths_template
  - unet_conf: default
  - _self_

hydra:
  run:
    dir: ${paths.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
  # - unet_segmentation
  # - inference
  - inference_for_pipeline

project_name: FIELD
task: # Leave empty as placeholder

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${data.datadir}/${job.job_now}

inference_for_pipeline:
  save_mask: False # If true, the segmented image will be saved
  overlay_comparison: False # If true, the original image and the segmented image will be overlayed
  side_by_side_comparison: True # If true, the original image and the segmented image will be displayed side by side but greatly increases the time to process