# All filesystem paths, built from base_dir + project‐specific subfolders
# conf/paths/default.yaml

base_dir: ${hydra:runtime.cwd}                      # usually the repo root
data_dir: ${paths.base_dir}/data

project_dir: ${paths.base_dir}/projects/${project.name}
project_mode_dir: ${paths.project_dir}/${mode} # e.g. projects/field/train

# Preprocess paths
project_preprocess_dir: ${paths.project_dir}/preprocess 
preprocess_split_dir: ${paths.project_preprocess_dir}/train_val_test_split 
project_datastats_dir: ${paths.project_preprocess_dir}/data_stats

# Preprocess stats and image list files
preprocess_stats_file: ${paths.project_preprocess_dir}/data_stats.txt
preprocess_image_list_file: ${paths.project_preprocess_dir}/images.txt

# Train, validation, and test directories for both images and masks
train_images_dir: ${paths.preprocess_split_dir}/train/images
train_masks_dir: ${paths.preprocess_split_dir}/train/masks
val_images_dir: ${paths.preprocess_split_dir}/val/images
val_masks_dir: ${paths.preprocess_split_dir}/val/masks
test_images_dir: ${paths.preprocess_split_dir}/test/images
test_masks_dir: ${paths.preprocess_split_dir}/test/masks

# hardcoded paths for each mode
project_train_dir: ${paths.project_dir}/train  
project_maskgen_dir: ${paths.project_dir}/mask_gen
project_inference_dir: ${paths.project_dir}/inference  

# paths for mask_gen mode:
mask_gen_cutout_dir: ${paths.project_maskgen_dir}/cutouts
refined_masks_dir: ${paths.project_maskgen_dir}/refined_masks
relabeled_masks_dir: ${paths.project_maskgen_dir}/relabeled_masks
voxel_inspection_results_dir: ${paths.project_maskgen_dir}/mask_inspection_db
voxel_inspection_results_db: ${paths.voxel_inspection_results_dir}/${project.name}_db.csv

# model paths
yolo_weed_detection_model: ${paths.data_dir}/field-tools/models/weed_detection/weights/best.pt
unet_segmentation_model: ${paths.data_dir}/field-tools/models/unet/unet_segmentation.pth

# DB paths
longterm_storage: /mnt/research-projects/r/raatwell/longterm_images3/
agir_field_db_dir: ${paths.longterm_storage}/field-tools/agir_field_db
agir_field_db: ${paths.agir_field_db_dir}/test_agir_field.db
agir_field_db_schema: ${paths.agir_field_db_dir}/schema.sql